name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCP
        run: |
          ssh fun_i_con@${{ secrets.SSH_HOST }} 'cd /var/www/html && sudo chmod -R 777 .'

          while IFS= read -r file; do
            rsync -avz -e "ssh" --exclude=".git" $file fun_i_con@${{ secrets.SSH_HOST }}:/var/www/html/
          done < deploy-list.txt
